In [1]:
%matplotlib inline

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import random

#### 輸入1~5的數字訂為n
#### 將會生出rank為n的5x5矩陣
#### 矩陣內數字從-6~6隨機選取

In [2]:
A = np.random.randint(-6,6,size=[5,5])
B = np.linalg.matrix_rank(A)
C = input('請輸入1~5的數字 ')
C = float(C)
while B!=C:
    A = np.random.randint(-6,6,size=[5,5])
    B = np.linalg.matrix_rank(A)
    if B==C:
        break
print(A,'產出的矩陣')
print('rank為',B)

請輸入1~5的數字 4
[[ 0  2  2 -5 -1]
 [-3 -3 -1  0  0]
 [-3 -2 -2 -3 -1]
 [-1  2 -5 -6 -5]
 [ 4  4  3 -3  2]] 產出的矩陣
rank為 4


### 我們用程式碼試著跑出rank5的結果

In [3]:
A = np.random.randint(-6,6,size=[5,5])
B = np.linalg.matrix_rank(A)
C = input('請輸入1~5的數字 ')
C = float(C)
while B!=C:
    A = np.random.randint(-6,6,size=[5,5])
    B = np.linalg.matrix_rank(A)
    if B==C:
        break
print(A,'產出的矩陣')
print('rank為',B)

請輸入1~5的數字 5
[[-3  1  0 -4 -5]
 [ 4 -1  1 -4 -1]
 [-4 -1 -4 -3 -1]
 [-1  0 -2 -1  5]
 [-2 -2  3 -2 -5]] 產出的矩陣
rank為 5
